#! /bin/bash

systemctl restart apache2
echo "http://your_address/phpmyadmin"

echo "______basephpmyadmin________"

echo "CREATE USER 'oksesaneka22'@'localhost' IDENTIFIED BY 'password';"
echo "GRANT ALL PRIVILEGES ON * . * TO 'newuser'@'localhost';"
echo "FLUSH PRIVILEGES;"
echo "exit"

mysql -u root -p


echo "______________create base in phpmyadmin________"
echo "name vp  codirovka   utf8_general_ci"
read phpmyadmin

cd /home/ubuntu/
curl -O https://wordpress.org/latest.tar.gz
tar xzvf latest.tar.gz
cd wordpress/
cp * -R /var/www/html/
cd /var/www/html/
chown -R www-data:www-data /var/www/html/



Yurii Levchu +++



test 


test


echo "Finish!!!!!!!!"
