global:
  resolve_timeout: 5m
  # Тут можна додати інші глобальні налаштування, якщо потрібно
  # наприклад, налаштування SMTP для email сповіщень
  # smtp_from: 'alertmanager@example.com'
  # smtp_smarthost: 'localhost:25'

# Секція шаблонів (необов'язково, але часто використовується для кастомізації повідомлень)
# templates:
# - '/etc/alertmanager/templates/*.tmpl'

# --- ОСНОВНА СЕКЦІЯ МАРШРУТИЗАЦІЇ ---
# Має бути тільки ОДИН блок 'route:' на верхньому рівні!
route:
  receiver: 'telegram'             # Отримувач за замовчуванням для всіх сповіщень
  group_by: ['alertname', 'job']   # Рекомендоване групування сповіщень
  group_wait: 30s                  # Час очікування перед відправкою першого сповіщення з групи
  group_interval: 5m               # Інтервал між відправками сповіщень для активної групи
  repeat_interval: 4h              # Інтервал для повторної відправки активних (не вирішених) сповіщень

  # Вкладені маршрути для більш специфічної обробки
  routes:
    # Цей маршрут обробляє сповіщення з severity "warning" або "critical"
    - receiver: 'telegram'         # Сповіщення, що відповідають, підуть цьому отримувачу
      group_wait: 10s              # Специфічний час очікування для цієї групи (з другого блоку 'route')
      matchers:
        - severity =~ "warning|critical|firing" # Умова для спрацювання цього маршруту
      # continue: false # За замовчуванням 'false'. Якщо 'true', сповіщення також піде шляхом батьківського маршруту.

# --- СЕКЦІЯ ОТРИМУВАЧІВ ---
# Має бути тільки ОДИН блок 'receivers:' на верхньому рівні!
receivers:
  - name: 'telegram' # Ім'я отримувача, яке використовується в 'route'
    telegram_configs:
      # Використовуємо токен та chat_id з вашого другого блоку,
      # оскільки там коректніші лапки для токена.
      # Додаємо 'send_resolved: true' з вашого першого блоку.
      - bot_token: "6687837790:AAEWWBV3NZHDft6q64ysU48CpUhMZa-uYvI"
        api_url: 'https://api.telegram.org' # Рекомендовано вказати явно
        chat_id: -370901112
        send_resolved: true # Надсилати повідомлення, коли алерт вирішено
        parse_mode: 'Markdown' # Або 'HTML', для форматування тексту повідомлень

# Ваші коментарі з кінця файлу:
#  https://api.telegram.org/botINSERT_BOT_ID_HERE/getUpdates - to get chat_id
#  amtool --alertmanager.url=http://localhost:9093/ alert add alertname="Test alert" severity="warning" job="test-job" - to send test alert
